### ISSUE TITLE
KeyError: 'logit'

### ISSUE THREAD

**Issue by bbb801** [sunlabuiuc/PyHealth#129]
Dear Sir/Madam,

I got an error when I ran the following codes (data is from Pipeline 5: Sleep Staging):

cal_model = HistogramBinning(model)
# cal_model =KCal(model)
# cal_model =TemperatureScaling(model)
cal_model.calibrate(cal_dataset=val_dataset)
from pyhealth.trainer import Trainer
print(Trainer(model=cal_model, metrics=['cwECEt_adapt', 'accuracy']).evaluate(test_loader))

![image](https://user-images.githubusercontent.com/52306405/231204129-29c09624-02a2-4714-9ced-08e89395acac.png)
![image](https://user-images.githubusercontent.com/52306405/231204312-072cf6c0-473a-43a1-8d38-94268168e1f9.png)

Any advice? Thank you.

**Comment by zlin7** [comment]
Hi Jundong,

Thanks for your email! This is because the model (ContraWR) doesn’t return logit yet. We haven’t got to push the changes that require all PyHealth model to return this necessary information. 

We are pushing an update now for other existing models – if you need it immediately you could manually change ContraWR’s forward method by adding something like https://github.com/sunlabuiuc/PyHealth/blob/3aec5f214e9f5e38b987b6fa9f13443abd3ec3fd/pyhealth/models/sparcnet.py#L345. 

Best,
Zhen

**Comment by ycq091044** [comment]
[Update] Thanks, we made changes to the ContraWR model. Please pull the new changes, and the error should be gone.

**Comment by bbb801** [comment]
Thank you, Chaoqi and Zhan.

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Chaoqi Yang ***@***.***>
Sent: Wednesday, April 12, 2023 8:54:41 AM
To: sunlabuiuc/PyHealth ***@***.***>
Cc: Dr. LIU Jundong ***@***.***>; Author ***@***.***>
Subject: [Ext] Re: [sunlabuiuc/PyHealth] KeyError: 'logit' (Issue #129)

This email originated from outside of City University of Hong Kong. Do not reply, click links, or open attachments unless you confirm the identity of the sender and know that the content is safe.


Closed #129<https://github.com/sunlabuiuc/PyHealth/issues/129> as completed.

―
