### ISSUE TITLE
Cannot download 'https://storage.googleapis.com/pyhealth/resource/NDC_to_ATC.csv'

### ISSUE THREAD

**Issue by junjzhang7** [sunlabuiuc/PyHealth#200]
When initialize the `MIMIC3Dataset()` class, I get `urllib.error.URLError`. And I checked the call stack, I found the problem lies in the function `download_and_read_csv()`  of the `CrossMap`  class. I think it's because of my own Internet connection, while I hope to open the local download permission for these files and alternate network download with local file reading.

**Comment by AJ-Fresnel** [comment]
Hello^ ^, I have also encountered this issue and I am unable to access it https://storage.googleapis.com/pyhealth/resource/NDC_to_CCSCM.csv 
Have you solved this problem yet?

**Comment by pat-jj** [comment]
Hi, thanks for the question.
Could you share the code for the `MIMIC3Dataset()` initialization?
By the way, `NDC_to_CCSCM.csv` does not exist as NDC is a vocabulary for drugs while CCSCM is a vocabulary for conditions.

**Comment by junjzhang7** [comment]
Of course, thanks for your reply. Here is the code for the `MIMIC3Dataset() ` initialization. And the `root` is the file's local path, which includes `DIAGNOSES_ICD.csv`, `PROCEDURES_ICD.csv`, and `PRESCRIPTIONS.csv`.
<img width="777" alt="截屏2023-08-23 12 10 08" src="https://github.com/sunlabuiuc/PyHealth/assets/140708490/6fefa35d-a316-4a98-ae6e-d1ce10856d6a">
 I get the `urllib.error.URLError` when the function `download_and_read_csv()` tries to download the `NDC_to_ATC.csv`.
<img width="970" alt="截屏2023-08-23 12 27 00" src="https://github.com/sunlabuiuc/PyHealth/assets/140708490/f24e0c2a-97d1-4c02-8832-8799f04976ce">

**Comment by pat-jj** [comment]
The code mapping file `xxx.csv` is downloaded and stored as `.cache/pyhealth/medcode/xxx.csv` in your home directory.
`urllib.error.URLError` may due to the network problem downloading file from our Google Cloud Server.
As an alternative solution, we have uploaded a zipped file containing all the mapping files to [Google Drive](https://drive.google.com/file/d/1iCdOeBje5rtW3A-qDCem3m5TSG7F3zFp/view?usp=sharing)

You can download it, unzip it, and put all .csv files in `.cache/pyhealth/medcode/`, which should address the issue.

**Comment by junjzhang7** [comment]
It works! Thank you and your meaningful work! :thumbsup: :thumbsup:  :thumbsup:
